python data2db.py \
  --csv-file "data/merged.csv.sample" \
  --log-interval 3 \
  --publication-number "Publication number" \
  --publication-date "Publication date" \
  --patent-office "Patent office" \
  --application-filing-date "Application/filing date" \
  --applicants-bvd-id-numbers "Applicant(s) BvD ID Number(s)" \
  --backward-citations "Backward citations" \
  --forward-citations "Forward citations" \
  --abstract "Abstract"
